language: node_js
node_js:
- 4
- 5
- 6

notifications:
  email: false

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: CHsdfPU0lGXuPwaVdv5TMYT6QvhzjEDoZZfZklg+LJ6Fn0Y0dY8wObz/gwMNHbO7HirhAHJsZxKudPa0h+RAdV0kVgbYvjMLAmkOwXZY6TThkGnUE3EdRFo0rS/XyIg/zxES453GOaZbh01upiPRwsuQAZwGwIJ8YGYSS/PiR3HuI4rEb5Qs6h9EeuLgEpjEHjlAI5nTgoOAZY3oxu3t3g4zfDDT5EvVO611MGjsxqrh3Lgt96EfeI4h5VQ5jQzyWQMWD5MnqXwcyIWYjJt1CKx0nb7sh7yyrOEzn1Fpq+t4FRUhUVTbCY4MVlU1pfHSbWxR9zY1J1RDTtf/kwoIN59X5+QXA/5sssbLd+wuzCG8MIUzcAIb3N+tGHyLadMBOgBsBIa2dYkv05P54QAX8uDf1L9tvJoOsb6wd6QpVQF8LCclOAKWibXtHW82s7sev5lCuB8hHBzU3DmvbK7HkY434CSykyBc1zF6U2nY+vOyFO944az/vOyAyfUYgGwkXdQGUocxrPRxw4cjue37peHsdbEr12lwWbhHPa/6KyLCEJrs3fd1Hp9QdklY1qc2DJOnZaZdv/257KRdTDHrOFiGaGoVROVx7bhyTtJql4/IvENUhxVEW2qsXlxTf1SgqUbELX8PZpgFLr8eX1hS+6Yqwj5uCuMfN6Dm/nA2XOk=
  on:
    tags: true
    repo: trailsjs/trailpack-webpack
    node: 6
